/*
 * 商家主页.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import cilent.Core;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Rectangle;

/**
 *
 * @author  __USER__
 */
public class 商家主页 extends javax.swing.JFrame {
	private String USERID = "-1";
	private String sworks;
	private String[] works;
	private int Worknum = 0;
	/** Creates new form 商家主页 */
	public 商家主页(String USERID) {
		setBounds(new Rectangle(560, 110, 0, 0));
		this.USERID = USERID;
		initComponents();
		sworks = Core.EPGetWorkInfo(USERID);
		works = sworks.split("下一个");
		Worknum = works.length;
		System.out.println(Worknum);
		String work1,work2,work3 ;
		try {
			work1 = "<html>" + "工作名称:" + works[0].split(",")[1] + "<br>工作岗位:"
					+ works[0].split(",")[2] + "</html>";
		} catch (ArrayIndexOutOfBoundsException e) {
			work1="";
		}
		try {
			work2 = "<html>" + "工作名称:" + works[1].split(",")[1] + "<br>工作岗位:"
					+ works[1].split(",")[2] + "</html>";
		} catch (ArrayIndexOutOfBoundsException e) {
			work2="";
		}
		try {
			work3 = "<html>" + "工作名称:" + works[2].split(",")[1] + "<br>工作岗位:"
					+ works[2].split(",")[2] + "</html>";
		} catch (ArrayIndexOutOfBoundsException e) {
			work3="";
		}
		jLabel7.setText(work1);
		jLabel8.setText(work2);
		jLabel9.setText(work3);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("黑体", Font.PLAIN, 16));
		jButton2 = new javax.swing.JButton();
		jButton2.setFont(new Font("黑体", Font.PLAIN, 18));
		jButton2.setBackground(new Color(0, 153, 102));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("黑体", Font.PLAIN, 16));
		jButton3 = new javax.swing.JButton();
		jButton3.setFont(new Font("黑体", Font.PLAIN, 18));
		jButton3.setBackground(new Color(0, 153, 102));
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				职位详情.main(works[1]);
			}
		});
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("黑体", Font.PLAIN, 16));
		jButton4 = new javax.swing.JButton();
		jButton4.setFont(new Font("黑体", Font.PLAIN, 18));
		jButton4.setBackground(new Color(0, 153, 102));
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				职位详情.main(works[2]);
			}
		});
		jButton5 = new javax.swing.JButton();
		jButton5.setFont(new Font("黑体", Font.PLAIN, 18));
		jButton5.setBackground(new Color(255, 255, 255));
		jButton5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				商家资料修改.main(USERID);
			}
		});
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("黑体", Font.PLAIN, 16));
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new Font("黑体", Font.PLAIN, 16));
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setFont(new Font("黑体", Font.PLAIN, 16));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel2.setText("\u5de5\u4f5c\u5c97\u4f4d\u4e00");
		jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jButton2.setForeground(new Color(255, 255, 255));
		jButton2.setText("\u67e5\u770b\u8be6\u60c5");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("\u5de5\u4f5c\u5c97\u4f4d\u4e8c");
		jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jButton3.setForeground(new Color(255, 255, 255));
		jButton3.setText("\u67e5\u770b\u8be6\u60c5");

		jLabel4.setText("\u5de5\u4f5c\u5c97\u4f4d\u4e09");
		jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jButton4.setForeground(new Color(255, 255, 255));
		jButton4.setText("\u67e5\u770b\u8be6\u60c5");

		jButton5.setForeground(new Color(0, 204, 153));
		jButton5.setText("\u8d44\u6599\u4fee\u6539");

		jLabel7.setText("\u72b6\u6001");
		jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel8.setText("\u72b6\u6001");
		jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel9.setText("\u72b6\u6001");
		jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(商家主页.class.getResource("/img/3.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jLabel3, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
										.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
										.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
											.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
											.addGap(5))
										.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
											.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
												.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
											.addGap(4))))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)))
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 201, GroupLayout.PREFERRED_SIZE))
								.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(jButton2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
									.addPreferredGap(ComponentPlacement.RELATED, 87, Short.MAX_VALUE))))
						.addComponent(lblNewLabel_1, Alignment.TRAILING))
					.addGap(30))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
					.addGap(17)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
							.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
							.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)))
					.addGap(28)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButton3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel8, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
								.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(22)
							.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
					.addGap(77)
					.addComponent(lblNewLabel_1)
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 617, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		职位详情.main(works[0]);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 商家主页(args).setVisible(true);
			}
		});
	}
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	// End of variables declaration//GEN-END:variables

}