/*
 * 商家首页.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;

import cilent.Core;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Rectangle;

/**
 *
 * @author  __USER__
 */
public class 商家首页 extends javax.swing.JFrame {
	private String USERID = "-1";
	private String sworks;
	private String[] works;
	private int Worknum = 0;
	private int page = 0;
	/** Creates new form 商家首页 */
	public 商家首页(String args) {
		setBounds(new Rectangle(560, 110, 0, 0));
		this.USERID = args;
		initComponents();
		sworks = Core.EPGetWorkInfo(USERID);
		works = sworks.split("下一个");
		Worknum = works.length;
		System.out.println(Worknum);
		String work ;
		try {
			work = "<html>" + "工作名称:" + works[0].split(",")[1] + "<br>工作岗位:"
					+ works[0].split(",")[2] + "</html>";
		} catch (ArrayIndexOutOfBoundsException e) {
			work="";
		}

		jlb3.setText(work);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jButton1 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton3.setBackground(new Color(0, 204, 153));
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				商家工作管理.main(works[page].split(",")[0],USERID);
			}
		});
		jButton4 = new javax.swing.JButton();
		jButton4.setBackground(new Color(0, 204, 153));
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				page--;
				if (page==-1) {
					JOptionPane.showMessageDialog(null, "没有了", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
					page++;
				}else {
					String work = 
							"<html>"
							+ "工作名称:"+works[page].split(",")[1]
							+"<br>工作岗位:"+works[page].split(",")[2]
							+"</html>";
					jlb3.setText(work);
				}
			}
		});
		jButton7 = new javax.swing.JButton();
		jButton7.setBackground(new Color(0, 204, 153));
		jButton7.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				page++;
				if (page == Worknum) {
					JOptionPane.showMessageDialog(null, "没有了", "MESSAGE",
							JOptionPane.INFORMATION_MESSAGE);
					page--;
				} else {
					String work = "<html>" + "工作名称:" + works[page].split(",")[1]
							+ "<br>工作岗位:" + works[page].split(",")[2] + "</html>";
					jlb3.setText(work);
				}
			}
		});
		jButton6 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new Font("黑体", Font.PLAIN, 32));
		jLabel1.setText("\u5de5\u4f5c\u5c97\u4f4d\u7ba1\u7406");

		jButton1.setFont(new java.awt.Font("黑体", 0, 24));
		jButton1.setText("\u516c\u53f8\u4e3b\u9875");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton5.setBackground(new Color(0, 153, 102));
		jButton5.setFont(new java.awt.Font("黑体", 0, 24));
		jButton5.setForeground(new Color(255, 255, 255));
		jButton5.setText("\u5de5\u4f5c\u5c97\u4f4d\u53d1\u5e03\u7533\u8bf7");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jPanel2.setBackground(new java.awt.Color(204, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		
		jlb3 = new JLabel("New label");
		jlb3.setFont(new Font("宋体", Font.PLAIN, 18));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jlb3, GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jlb3, GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
		);
		jPanel3.setLayout(jPanel3Layout);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u5c97\u4f4d");

		jButton3.setFont(new java.awt.Font("黑体", 0, 24));
		jButton3.setForeground(new Color(255, 255, 255));
		jButton3.setText("\u67e5\u770b\u8be6\u60c5");

		jButton4.setFont(new java.awt.Font("黑体", 0, 24));
		jButton4.setForeground(new Color(255, 255, 255));
		jButton4.setText("\u67e5\u770b\u4e0a\u4e00\u4e2a");

		jButton7.setFont(new java.awt.Font("黑体", 0, 24));
		jButton7.setForeground(new Color(255, 255, 255));
		jButton7.setText("\u67e5\u770b\u4e0b\u4e00\u4e2a");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jButton3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton7))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				360,
																				360,
																				360)
																		.addComponent(
																				jLabel2))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												30,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton7)
														.addComponent(jButton4)
														.addComponent(jButton3))
										.addContainerGap()));

		jButton6.setBackground(new Color(0, 153, 102));
		jButton6.setFont(new java.awt.Font("黑体", 0, 24));
		jButton6.setForeground(new Color(255, 255, 255));
		jButton6.setText("\u516c\u53f8\u4e3b\u9875");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(商家首页.class.getResource("/img/3.png")));
		
		btnNewButton = new JButton("\u9000\u51FA\u767B\u5F55");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				登陆界面.main(null);
			    dispose();
			}
		});
		btnNewButton.setForeground(Color.WHITE);
		btnNewButton.setFont(new Font("黑体", Font.PLAIN, 18));
		btnNewButton.setBackground(new Color(0, 153, 102));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(1149)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(406)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(126)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(jButton5)
									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 251, GroupLayout.PREFERRED_SIZE))
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNewLabel_1))))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(23)
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
					.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
					.addGap(457))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(11)
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(11)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
						.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(45)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton5)
						.addComponent(jButton6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGap(50)
					.addComponent(lblNewLabel_1)
					.addGap(164)
					.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 989, Short.MAX_VALUE)
					.addGap(1))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 787, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		商家主页.main(USERID);
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		商家职位发布.main(USERID);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 商家首页(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JLabel jlb3;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	private JButton btnNewButton;
}