/*
 * 商家资料修改.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import cilent.Core;
import cilent.infor.collEmployer;
import cilent.infor.newWork;

import java.awt.event.ActionEvent;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 商家资料修改 extends javax.swing.JFrame {
	private String USERID="-1";
	/** Creates new form 商家资料修改 */
	public 商家资料修改(String USERID) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(商家资料修改.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		this.USERID = USERID;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setForeground(new Color(255, 255, 255));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setForeground(new Color(255, 255, 255));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setForeground(new Color(255, 255, 255));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setForeground(new Color(255, 255, 255));
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				collEmployer c1 = new collEmployer();
				c1.setCname(jTextField1.getText());
				c1.setCaddress(jTextField2.getText());
				c1.setCnumber(jTextField3.getText());
				c1.setCresume(jTextArea1.getText());
				if (Core.changeEPInfo(USERID+","+c1.toString()).equals("true")) {
					JOptionPane.showMessageDialog(null,"修改成功", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
					dispose();
				}else {
					JOptionPane.showMessageDialog(null,"修改失败", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new java.awt.Font("黑体", 0, 36));
		jLabel1.setText("\u6211\u7684\u5546\u5bb6\u8d44\u6599");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel2.setText("\u4f01\u4e1a\u540d\u79f0\uff1a");

		jLabel3.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel3.setText("\u4f01\u4e1a\u8be6\u7ec6\u5730\u5740\uff1a");

		jLabel4.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel4.setText("\u5de5\u5546\u6ce8\u518c\u53f7\u7801\uff1a");

		jLabel5.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel5.setText("\u4f01\u4e1a\u7b80\u4ecb\uff1a");

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setText("\u786e\u8ba4\u4fee\u6539");
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		jTextArea1 = new javax.swing.JTextArea();
		
				jTextArea1.setColumns(20);
				jTextArea1.setRows(5);
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(商家资料修改.class.getResource("/img/8.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(22)
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(1166, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(194)
									.addComponent(jLabel5))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(159)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel2, Alignment.TRAILING)
										.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
							.addGap(17))
						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
							.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(lblNewLabel_1)
							.addGap(94)))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 232, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
							.addComponent(jTextArea1, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
									.addComponent(jTextField2, Alignment.LEADING)
									.addComponent(jTextField1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
									.addComponent(jLabel1, Alignment.LEADING)
									.addComponent(jTextField3, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
								.addGap(305)))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(9)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(lblNewLabel_1)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(jLabel1)
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(jLabel3)
									.addGap(27)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4)))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(12)
									.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)))
							.addGap(30)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jTextArea1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
							.addGap(47)
							.addComponent(jButton1)))
					.addContainerGap(67, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 803, Short.MAX_VALUE)
					.addGap(1))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 商家资料修改(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	// End of variables declaration//GEN-END:variables

}