/*
 * 商家职位发布.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import cilent.Core;
import cilent.infor.newWork;

import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 商家职位发布 extends javax.swing.JFrame {
	private String USERID = "-1";
	/** Creates new form 商家职位发布 */
	public 商家职位发布(String USERID) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(商家职位发布.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		this.USERID = USERID;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jFormattedTextField1 = new javax.swing.JFormattedTextField();
		jFormattedTextField3 = new javax.swing.JFormattedTextField();
		jFormattedTextField1_1 = new JFormattedTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jFormattedTextField4 = new javax.swing.JFormattedTextField();
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				newWork nw =new newWork();
				nw.setWorkname(jFormattedTextField1_1.getText());
				nw.setCompanyname(jFormattedTextField1.getText());
				nw.setJob(jFormattedTextField3.getText());
				nw.setWorkcontent(jTextArea1.getText());
				nw.setTelephone_number(jFormattedTextField4.getText());
				nw.setMoney(jFormattedTextField5.getText());
				nw.setEmployer(USERID);
				String result = Core.newWorks(nw.toString());
				System.out.println(result);
				if (result.equals("true")) {
					JOptionPane.showMessageDialog(null,"申请提交成功", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
					dispose();
				}else {
					JOptionPane.showMessageDialog(null,"提交失败", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});
		jFormattedTextField5 = new javax.swing.JFormattedTextField();
		jLabel8 = new javax.swing.JLabel();

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new java.awt.Font("黑体", 0, 36));
		jLabel1.setText("\u5de5\u4f5c\u5c97\u4f4d\u53d1\u5e03\u7533\u8bf7");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u516c\u53f8\u540d\u79f0");

		jLabel4.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u62db\u8058\u5c97\u4f4d");

		jLabel5.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u804c\u4f4d\u8be6\u60c5");

		jLabel6.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u8054\u7cfb\u7535\u8bdd");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jFormattedTextField4
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jFormattedTextField4ActionPerformed(evt);
					}
				});

		jButton1.setFont(new java.awt.Font("黑体", 0, 24));
		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setText("\u7533\u8bf7\u53d1\u5e03");

		jFormattedTextField5
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jFormattedTextField5ActionPerformed(evt);
					}
				});

		jLabel8.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u63a8\u5e7f\u7ade\u4ef7\u91d1\u989d");
		
		
		
		JLabel jLabel2_1 = new JLabel();
		jLabel2_1.setText("\u5DE5\u4F5C\u540D\u79F0");
		jLabel2_1.setForeground(Color.WHITE);
		jLabel2_1.setFont(new Font("黑体", Font.PLAIN, 24));
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(商家职位发布.class.getResource("/img/8.png")));
		
		lblNewLabel_2 = new JLabel("");
		lblNewLabel_2.setIcon(new ImageIcon(商家职位发布.class.getResource("/img/9.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(75)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel4)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jFormattedTextField3, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel5)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel2)
								.addComponent(jLabel2_1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 510, GroupLayout.PREFERRED_SIZE)
								.addComponent(jFormattedTextField1_1, GroupLayout.PREFERRED_SIZE, 510, GroupLayout.PREFERRED_SIZE))))
					.addGap(75))
				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(614, Short.MAX_VALUE))
				.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
					.addGap(231)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(231, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(46)
							.addComponent(lblNewLabel_1)
							.addPreferredGap(ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
							.addComponent(lblNewLabel_2)
							.addGap(40)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(30)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel8)
								.addComponent(jLabel6))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jFormattedTextField4, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
								.addComponent(jFormattedTextField5, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))))
					.addGap(72))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(40)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(77)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jFormattedTextField1_1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2_1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel4)
						.addComponent(jFormattedTextField3, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel5)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
						.addComponent(jFormattedTextField4, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
						.addComponent(jFormattedTextField5, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(54)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblNewLabel_2)
								.addComponent(lblNewLabel_1))))
					.addGap(83))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jFormattedTextField5ActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jFormattedTextField4ActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 商家职位发布(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JFormattedTextField jFormattedTextField3;
	private javax.swing.JFormattedTextField jFormattedTextField4;
	private javax.swing.JFormattedTextField jFormattedTextField5;
	private javax.swing.JFormattedTextField jFormattedTextField1_1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	private JLabel lblNewLabel_2;
}