/*
 * 应聘者详情.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;

import cilent.Core;

import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author  __USER__
 */
public class 应聘者详情 extends javax.swing.JFrame {
	private String tmp;
	private String epid;
	private String apid;
	private String workid;
	private String text;
	/** Creates new form 应聘者详情 */
	public 应聘者详情(String tmp,String epid,String workid) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(应聘者详情.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		initComponents();
		this.tmp = tmp;
		this.epid = epid;
		this.workid = workid;
		text = "<html>名字:"+tmp.split(",")[0]
					+"<br>年龄:"+tmp.split(",")[1]
					+"<br>性别:"+tmp.split(",")[2]
					+"<br>学历:"+tmp.split(",")[3]
					+"<br>身份证:"+tmp.split(",")[4]
					+"<br>手机号码:"+tmp.split(",")[5]
					+ "</html>";
		apid=tmp.split(",")[6];
		userinfo.setText(text);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton11.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (Core.EPpassAPformUser(apid+","+workid).equals("true")) {
					JOptionPane.showMessageDialog(null, "应聘成功", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}else {
					JOptionPane.showMessageDialog(null, "应聘失败", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel1.setText("\u5e94\u8058\u8005\u8be6\u60c5");
		
		userinfo = new JLabel("New label");
		userinfo.setFont(new Font("黑体", Font.PLAIN, 20));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGap(24)
					.addComponent(userinfo, GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
					.addGap(46))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(userinfo, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
					.addContainerGap())
		);
		jPanel2.setLayout(jPanel2Layout);

		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.setFont(new java.awt.Font("黑体", 0, 18));
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("\u804a\u5929");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton11.setBackground(new Color(0, 153, 102));
		jButton11.setFont(new java.awt.Font("黑体", 0, 18));
		jButton11.setForeground(new java.awt.Color(255, 255, 255));
		jButton11.setText("\u62db\u8058");

		jButton2.setBackground(new Color(0, 153, 102));
		jButton2.setFont(new java.awt.Font("黑体", 0, 18));
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("\u5bfc\u51fa\u7b80\u5386");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(应聘者详情.class.getResource("/img/3.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(279)
					.addComponent(jLabel1)
					.addContainerGap(567, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(822, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap(205, Short.MAX_VALUE)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(46))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(lblNewLabel_1)
							.addGap(141))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(93)
							.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
							.addGap(89)
							.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
							.addGap(96)
							.addComponent(jButton11, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)))
					.addGap(103))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel1))
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton11, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
						.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
						.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String address = JOptionPane.showInputDialog(null, "请输入导出文件简历地址(简历需要按照格式编写)", ".\\导出简历.txt");
		try {
			Core.outputfile(address, text);
			JOptionPane.showMessageDialog(null, "导出成功", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "导出失败", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
		}
		
		
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		管理员与商家对话2.main(epid);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args,final String id,final String workid) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 应聘者详情(args,id,workid).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	JLabel userinfo;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
}