/*
 * 用户首页.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cilent.Core;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author  __USER__
 */
public class 用户首页 extends javax.swing.JFrame {
	private String USERID = "-1";
	private String sworks;
	private String[] works;
	private int Worknum = 0;
	private int page = 0;

	/** Creates new form 用户首页 */
	public 用户首页(String USERID) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(用户首页.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		this.USERID = USERID;
		initComponents();
		sworks = Core.GetWorkInfo("0");
		init();
		jLabel1.setText(Core.GetAD("1"));
		/*
		"<html>公司名称:" + works[0].split(",")[1]
		+ "<br>工作名称:"+works[0].split(",")[0]
		+"<br>工作岗位:"+works[0].split(",")[2]
		+"<br>职位详细:"+works[0].split(",")[3]
		+"<br>工作ID:"+works[0].split(",")[4]	
		+"<br>雇主ID:"+works[0].split(",")[5]	
		+"</html>";
		 */
		
	}
	private void init() {
		page=0;
		works = sworks.split("下一个");
		Worknum = works.length;
		System.out.println(Worknum);
		String work;
		try {
			work = "<html>" + "工作名称:" + works[0].split(",")[1] + "<br>工作岗位:"
					+ works[0].split(",")[2] + "</html>";
		} catch (Exception e) {
			work = "空空如也";
		}

		jLabel2.setText(work);
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jFormattedTextField1 = new javax.swing.JFormattedTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton2.setBackground(new Color(255, 255, 255));
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				用户主页.main(USERID);
			}
		});
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("黑体", Font.PLAIN, 16));
		jButton3 = new javax.swing.JButton();
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				用户应聘兼职.main(works[page],USERID);
			}
		});
		jButton4 = new javax.swing.JButton();
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				page--;
				if (page==-1) {
					JOptionPane.showMessageDialog(null, "没有了", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
					page++;
				}else {
					String work = 
							"<html>"
							+ "工作名称:"+works[page].split(",")[1]
							+"<br>工作岗位:"+works[page].split(",")[2]
							+"</html>";
					jLabel2.setText(work);
				}
			}
		});
		jButton5 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u5e7f\u544a\u6846");
		jLabel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.setFont(new java.awt.Font("黑体", 0, 18));
		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setText("\u641c\u7d22");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("黑体", 0, 24));
		jButton2.setForeground(new Color(0, 204, 153));
		jButton2.setText("\u6211\u7684\u4e3b\u9875");

		jLabel2.setText("\u804c\u4f4d\u8be6\u60c5");
		jLabel2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jButton3.setBackground(new Color(0, 153, 102));
		jButton3.setFont(new java.awt.Font("黑体", 0, 18));
		jButton3.setForeground(new Color(255, 255, 255));
		jButton3.setText("\u67e5\u770b\u8be6\u60c5");

		jButton4.setBackground(new Color(0, 153, 102));
		jButton4.setFont(new java.awt.Font("黑体", 0, 18));
		jButton4.setForeground(new Color(255, 255, 255));
		jButton4.setText("\u4e0a\u4e00\u5c97\u4f4d");

		jButton5.setBackground(new Color(0, 153, 102));
		jButton5.setFont(new java.awt.Font("黑体", 0, 18));
		jButton5.setForeground(new Color(255, 255, 255));
		jButton5.setText("\u4e0b\u4e00\u5c97\u4f4d");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGap(24)
					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 496, GroupLayout.PREFERRED_SIZE)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addContainerGap())
						.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jButton5, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
								.addComponent(jButton4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
							.addContainerGap())))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
					.addContainerGap())
		);
		jPanel2.setLayout(jPanel2Layout);
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(用户首页.class.getResource("/img/3.png")));
		
		JButton btnNewButton_1 = new JButton("\u9000\u51FA\u767B\u5F55");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				登陆界面.main(null);
				dispose();
			}
		});
		btnNewButton_1.setForeground(Color.WHITE);
		btnNewButton_1.setFont(new Font("黑体", Font.PLAIN, 18));
		btnNewButton_1.setBackground(new Color(0, 153, 102));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 531, Short.MAX_VALUE)
					.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(62)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 392, GroupLayout.PREFERRED_SIZE)
									.addGap(27)
									.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 641, GroupLayout.PREFERRED_SIZE)
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 652, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(37)
							.addComponent(lblNewLabel_1)))
					.addContainerGap(19, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
					.addGap(28)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
					.addGap(27)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(lblNewLabel_1)
					.addGap(97))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 716, Short.MAX_VALUE)
					.addGap(1))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		page++;
		if (page >= Worknum) {
			JOptionPane.showMessageDialog(null, "没有了", "MESSAGE",
					JOptionPane.INFORMATION_MESSAGE);
			page--;
		} else {
			String work = "<html>" + "工作名称:" + works[page].split(",")[1]
					+ "<br>工作岗位:" + works[page].split(",")[2] + "</html>";
			jLabel2.setText(work);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		sworks = Core.Usearchwork(jFormattedTextField1.getText());
		System.out.println(sworks);
		init();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 用户首页(args).setVisible(true);
			}
		});
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
}