/*
 * 用户注册.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;

import javax.swing.JOptionPane;

import cilent.Core;
import cilent.infor.regAdmin;
import cilent.infor.regUser;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 用户注册 extends javax.swing.JFrame {

	/** Creates new form 用户注册 */
	public 用户注册() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(用户注册.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jFormattedTextField1 = new javax.swing.JFormattedTextField();
		jFormattedTextField2 = new javax.swing.JFormattedTextField();
		jTextField1 = new javax.swing.JTextField();
		jFormattedTextField3 = new javax.swing.JFormattedTextField();
		jFormattedTextField4 = new javax.swing.JFormattedTextField();
		jFormattedTextField5 = new javax.swing.JFormattedTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel10 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();
		jFormattedTextField6 = new javax.swing.JFormattedTextField();
		jButton1 = new javax.swing.JButton();
		jButton1.setForeground(new Color(255, 255, 255));

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new Font("黑体", Font.PLAIN, 36));
		jLabel1.setForeground(new java.awt.Color(240, 240, 240));
		jLabel1.setText("\u7528\u6237\u6ce8\u518c");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel2.setForeground(new java.awt.Color(240, 240, 240));
		jLabel2.setText("\u5e10\u53f7");

		jLabel3.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel3.setForeground(new java.awt.Color(240, 240, 240));
		jLabel3.setText("\u5bc6\u7801");

		jLabel4.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel4.setForeground(new java.awt.Color(240, 240, 240));
		jLabel4.setText("\u59d3\u540d");

		jLabel5.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel5.setForeground(new java.awt.Color(240, 240, 240));
		jLabel5.setText("\u5e74\u9f84");

		jLabel6.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel6.setForeground(new java.awt.Color(240, 240, 240));
		jLabel6.setText("\u6027\u522b");

		jLabel7.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel7.setForeground(new java.awt.Color(240, 240, 240));
		jLabel7.setText("\u5b66\u5386");

		jLabel8.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel8.setForeground(new java.awt.Color(240, 240, 240));
		jLabel8.setText("\u8054\u7cfb\u65b9\u5f0f");

		jLabel9.setFont(new Font("黑体", Font.PLAIN, 24));
		jLabel9.setForeground(new java.awt.Color(240, 240, 240));
		jLabel9.setText("\u8eab\u4efd\u8bc1\u53f7\u7801");

		jFormattedTextField2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jFormattedTextField2ActionPerformed(evt);
					}
				});

		jLabel10.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel10.setForeground(new java.awt.Color(240, 240, 240));
		jLabel10.setText("\u786e\u8ba4\u5bc6\u7801");

		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.setFont(new Font("黑体", Font.PLAIN, 26));
		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(用户注册.class.getResource("/img/3.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(10)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
									.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
									.addComponent(jLabel4)
									.addComponent(jLabel7)
									.addComponent(jLabel9)))
							.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addGap(106)
								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)))
						.addComponent(jLabel10)
						.addComponent(jLabel2))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jFormattedTextField6, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(jFormattedTextField4, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
										.addComponent(jFormattedTextField2, GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup()
											.addComponent(jLabel6)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(ComponentPlacement.UNRELATED)
											.addComponent(jLabel5)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(jFormattedTextField3, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup()
											.addComponent(jLabel8)
											.addPreferredGap(ComponentPlacement.RELATED)
											.addComponent(jFormattedTextField5, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)))
									.addGap(14))
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
									.addComponent(jPasswordField2, Alignment.LEADING)
									.addComponent(jPasswordField1, Alignment.LEADING)
									.addComponent(jFormattedTextField1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addContainerGap(17, GroupLayout.PREFERRED_SIZE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(lblNewLabel_1)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(269)
					.addComponent(jLabel1)
					.addContainerGap(283, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(240)
					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(240, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(51))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel3)
						.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jPasswordField2, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
									.addComponent(jLabel4)
									.addComponent(jLabel6))
								.addGroup(Alignment.TRAILING, jPanel1Layout.createParallelGroup(Alignment.BASELINE)
									.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
									.addComponent(jLabel5))
								.addComponent(jFormattedTextField3, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(jFormattedTextField2, GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel7)
						.addComponent(jFormattedTextField4, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel8)
						.addComponent(jFormattedTextField5, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel9)
						.addComponent(jFormattedTextField6, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
					.addGap(111)
					.addComponent(lblNewLabel_1)
					.addGap(173))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 706, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 672, Short.MAX_VALUE)
					.addGap(1))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		regUser rU = new regUser();
		rU.setName(jFormattedTextField1.getText());
		rU.setPw(String.copyValueOf(jPasswordField1.getPassword()));
		rU.setPersonalname(jFormattedTextField2.getText());
		rU.setSex(jTextField1.getText());
		rU.setAge(jFormattedTextField3.getText());
		rU.setQualification(jFormattedTextField4.getText());
		rU.setTelephonenumber(jFormattedTextField5.getText());
		rU.setId_card(jFormattedTextField6.getText());
		String rString=Core.regU(rU.toString());
		System.out.println(rString);
		if (rString.equals("true")) {
			JOptionPane.showMessageDialog(null,"注册成功", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
			dispose();
		}else {
			JOptionPane.showMessageDialog(null,"注册失败", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void jFormattedTextField2ActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 用户注册().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JFormattedTextField jFormattedTextField2;
	private javax.swing.JFormattedTextField jFormattedTextField3;
	private javax.swing.JFormattedTextField jFormattedTextField4;
	private javax.swing.JFormattedTextField jFormattedTextField5;
	private javax.swing.JFormattedTextField jFormattedTextField6;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTextField jTextField1;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	// End of variables declaration//GEN-END:variables

}