/*
 * 用户主页.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import cilent.Core;

import javax.swing.GroupLayout.Alignment;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import javax.swing.JButton;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 用户主页 extends javax.swing.JFrame {
	private String USERID = "-1";
	private String isVIP;
	private String nowWork;
	/** Creates new form 用户主页 */
	public 用户主页(String USERID) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(用户主页.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		initComponents();
		this.USERID = USERID;
		isVIP = Core.GetVIP(USERID);
		if (isVIP.equals("true")) {
			jLabel3.setText("VIP");
		}else {
			jLabel3.setText("点击充值VIP");
		}
		nowWork = Core.getmywork(USERID);
		System.out.println(nowWork);
		try {
			mywork.setText("<html>" + "工作名称:" + nowWork.split(",")[1] + "<br>工作岗位:"
					+ nowWork.split(",")[2] + "</html>");
		} catch (Exception e) {
			mywork.setText("无工作");
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jLabel1.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				用户资料修改.main(USERID);
			}
		});
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel3.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				String address = JOptionPane.showInputDialog(null, "会员激活码：", "YES");
				if (address.equals("YES")) {
					if(Core.SetVIP(USERID).equals("true")) {
						JOptionPane.showMessageDialog(null, "充值成功", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
					}
				}
			}
		});
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setForeground(new Color(255, 255, 255));
		jPanel2 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setText("\u6211");
		jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setText("\u8d44\u6599\u4fee\u6539");
		jButton1.setActionCommand("jButton1");

		jLabel2.setFont(new Font("黑体", Font.PLAIN, 20));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u4F1A\u5458\u72B6\u6001:");
		jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel4.setFont(new Font("黑体", Font.PLAIN, 20));
		jLabel4.setText("\u6211\u7684\u5de5\u4f5c");
		
		mywork = new JLabel("");
		mywork.setFont(new Font("黑体", Font.PLAIN, 20));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addComponent(mywork, GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
					.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(mywork, GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
		);
		jPanel2.setLayout(jPanel2Layout);
		
		lblNewLabel = new JLabel("");
		lblNewLabel.setIcon(new ImageIcon(用户主页.class.getResource("/img/3.png")));
		
		lblNewLabel_1 = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel_1.setForeground(Color.WHITE);
		lblNewLabel_1.setFont(new Font("华文彩云", Font.PLAIN, 36));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(56)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(6)
							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
							.addGap(36)
							.addComponent(jLabel2)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(59, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblNewLabel)
					.addGap(23))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(597, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel4)
							.addPreferredGap(ComponentPlacement.RELATED))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
							.addGap(52)))
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblNewLabel)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE)
					.addGap(1))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 用户主页(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private JLabel mywork;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
}