/*
 * 用户资料修改.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import cilent.Core;
import cilent.infor.collUser;

import java.awt.event.ActionEvent;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 用户资料修改 extends javax.swing.JFrame {
	private String USERID = "-1";
	
	/** Creates new form 用户资料修改 */
	public 用户资料修改(String USERID) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(用户资料修改.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		initComponents();this.USERID = USERID;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setForeground(new Color(255, 255, 255));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setForeground(new Color(255, 255, 255));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setForeground(new Color(255, 255, 255));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setForeground(new Color(255, 255, 255));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setForeground(new Color(255, 255, 255));
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setForeground(new Color(255, 255, 255));
		jTextField1 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				collUser C1 = new collUser();
				C1.setPersonalname(jTextField1.getText());
				C1.setSex(jTextField2.getText());
				C1.setAge(jTextField3.getText());
				C1.setQualification(jTextField4.getText());
				C1.setTelephonenumber(jTextField5.getText());
				C1.setId_card(jTextField6.getText());
				if (Core.changeURInfo(USERID+","+C1.toString()).equals("true")) {
					JOptionPane.showMessageDialog(null,"修改成功", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
					dispose();
				}else {
					JOptionPane.showMessageDialog(null,"修改失败", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});
		jButton2 = new javax.swing.JButton();
		jButton2.setBackground(new Color(0, 153, 102));
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String address = JOptionPane.showInputDialog(null, "请输入文件简历地址(简历需要按照格式编写)", ".\\简历.txt");
				collUser c1 = null;
				try {
					c1 = Core.ReadFromFile(address);
				} catch (Exception e2) {
					JOptionPane.showMessageDialog(null, "导入失败\n可能的原因:1.格式不对 2.找不到文件", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}
				if (c1 !=null) {
					jTextField1.setText(c1.getPersonalname());
					jTextField2.setText(c1.getSex());
					jTextField3.setText(c1.getAge());
					jTextField4.setText(c1.getQualification());
					jTextField5.setText(c1.getTelephonenumber());
					jTextField6.setText(c1.getId_card());
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new Color(0, 204, 153));

		jLabel1.setFont(new java.awt.Font("黑体", 0, 36));
		jLabel1.setText("\u6211\u7684\u8d44\u6599");

		jLabel2.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel2.setText("\u59d3\u540d\uff1a");

		jLabel3.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel3.setText("\u6027\u522b\uff1a");

		jLabel4.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel4.setText("\u5e74\u9f84\uff1a");

		jLabel5.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel5.setText("\u5b66\u5386\uff1a");

		jLabel6.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel6.setText("\u8054\u7cfb\u65b9\u5f0f\uff1a");

		jLabel7.setFont(new java.awt.Font("黑体", 0, 24));
		jLabel7.setText("\u8eab\u4efd\u8bc1\u53f7\u7801\uff1a");

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setText("\u786e\u8ba4\u4fee\u6539");

		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setForeground(new Color(255, 255, 255));
		jButton2.setText("\u5bfc\u5165\u7b80\u5386");
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setForeground(Color.WHITE);
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(用户资料修改.class.getResource("/img/8.png")));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(jLabel7)
										.addComponent(jLabel3)
										.addComponent(jLabel4)
										.addComponent(jLabel6)
										.addComponent(jLabel5)
										.addComponent(jLabel2))
									.addPreferredGap(ComponentPlacement.RELATED)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
										.addComponent(jTextField3, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
										.addComponent(jTextField4, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
										.addComponent(jTextField5, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
										.addComponent(jTextField2, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
										.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 270, GroupLayout.PREFERRED_SIZE))
									.addGap(176))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(146)
									.addComponent(jLabel1)
									.addContainerGap())))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(36)
							.addComponent(lblNewLabel_1)
							.addGap(53)
							.addComponent(jButton1)
							.addGap(123)
							.addComponent(jButton2)
							.addContainerGap())))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(13)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
							.addGap(39))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel4)
						.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel7))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(62)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jButton1)
								.addComponent(jButton2)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(lblNewLabel_1)))
					.addContainerGap(68, Short.MAX_VALUE))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 用户资料修改(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
	// End of variables declaration//GEN-END:variables

}