/*
 * 登陆界面.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import cilent.Core;

import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 登陆界面 extends javax.swing.JFrame {

	/** Creates new form 登陆界面 */
	public 登陆界面() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(登陆界面.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		getContentPane().setForeground(new Color(204, 51, 0));
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		panel = new JPanel();
		panel.setForeground(new Color(255, 255, 255));
		panel.setBackground(new Color(0, 204, 153));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 732, Short.MAX_VALUE)
					.addGap(1))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(panel, GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
		);
																												
																												JLabel lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
																												lblNewLabel.setForeground(new Color(255, 255, 255));
																												lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
																												panel.add(lblNewLabel);
																												
																												lblNewLabel_1 = new JLabel("");
																												lblNewLabel_1.setIcon(new ImageIcon(登陆界面.class.getResource("/img/3.png")));
																												panel.add(lblNewLabel_1);
																										
																												jPanel1 = new javax.swing.JPanel();
																												panel.add(jPanel1);
																												jLabel2 = new javax.swing.JLabel();
																												jLabel3 = new javax.swing.JLabel();
																												jLabel3.setIcon(new ImageIcon(登陆界面.class.getResource("/img/4.PNG")));
																												jLabel4 = new javax.swing.JLabel();
																												jLabel4.setIcon(new ImageIcon(登陆界面.class.getResource("/img/6.PNG")));
																												jFormattedTextField1 = new javax.swing.JFormattedTextField();
																												jPasswordField1 = new javax.swing.JPasswordField();
																												jButton1 = new javax.swing.JButton();
																												jButton1.setForeground(new Color(255, 255, 255));
																												jButton1.addActionListener(new ActionListener() {
																													public void actionPerformed(ActionEvent e) {
																														String tmp = Core.login(jFormattedTextField1.getText(),
																																String.copyValueOf(jPasswordField1.getPassword()));
																														try {
																															if (tmp.split(",")[1].equals("user")) {
																																//login.setVisible(false);
																																dispose();
																																用户首页.main(tmp.split(",")[0]);
																															} else if (tmp.split(",")[1].equals("employer")) {
																																//login.setVisible(false);
																																dispose();
																																商家首页.main(tmp.split(",")[0]);
																															} else if (tmp.split(",")[1].equals("admin")) {
																																//login.setVisible(false);
																																dispose();
																																管理员管理应用.main(null);
																															}
																														} catch (Exception e2) {
																															JOptionPane.showMessageDialog(null, "登陆失败", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
																														}
																													}
																												});
																												jButton2 = new javax.swing.JButton();
																												jButton2.setForeground(new Color(255, 255, 255));
																												jButton2.setFont(new Font("黑体", Font.PLAIN, 15));
																												jButton3 = new javax.swing.JButton();
																												jButton3.setForeground(new Color(255, 255, 255));
																												jButton3.setFont(new Font("黑体", Font.PLAIN, 15));
																												jButton4 = new javax.swing.JButton();
																												jButton4.setForeground(new Color(255, 255, 255));
																												jButton4.setFont(new Font("黑体", Font.PLAIN, 15));
																												jButton4.addActionListener(new ActionListener() {
																													public void actionPerformed(ActionEvent e) {
																														管理员注册.main(null);
																													}
																												});
																												
																														jPanel1.setBackground(new Color(255, 255, 255));
																														jPanel1.setMaximumSize(new Dimension(10000, 10000));
																														
																																jLabel2.setFont(new Font("黑体", Font.PLAIN, 36));
																																jLabel2.setForeground(new Color(102, 204, 153));
																																jLabel2.setText("\u767b\u5f55");
																																
																																		jLabel3.setFont(new java.awt.Font("黑体", 0, 24));
																																		jLabel3.setForeground(new java.awt.Color(240, 240, 240));
																																		jLabel3.setText("\r\n");
																																		
																																				jLabel4.setFont(new java.awt.Font("黑体", 0, 24));
																																				jLabel4.setForeground(new java.awt.Color(240, 240, 240));
																																				
																																						jFormattedTextField1
																																								.addActionListener(new java.awt.event.ActionListener() {
																																									public void actionPerformed(java.awt.event.ActionEvent evt) {
																																										jFormattedTextField1ActionPerformed(evt);
																																									}
																																								});
																																						
																																								jButton1.setBackground(new Color(0, 204, 153));
																																								jButton1.setFont(new java.awt.Font("黑体", 0, 24));
																																								jButton1.setText("\u767b\u5f55");
																																								
																																										jButton2.setBackground(new Color(0, 204, 153));
																																										jButton2.setText("\u7528\u6237\u6ce8\u518c");
																																										jButton2.addActionListener(new java.awt.event.ActionListener() {
																																											public void actionPerformed(java.awt.event.ActionEvent evt) {
																																												jButton2ActionPerformed(evt);
																																											}
																																										});
																																										
																																												jButton3.setBackground(new Color(0, 204, 153));
																																												jButton3.setText("\u5546\u5bb6\u6ce8\u518c");
																																												jButton3.addActionListener(new java.awt.event.ActionListener() {
																																													public void actionPerformed(java.awt.event.ActionEvent evt) {
																																														jButton3ActionPerformed(evt);
																																													}
																																												});
																																												
																																														jButton4.setBackground(new Color(0, 204, 153));
																																														jButton4.setText("\u7ba1\u7406\u5458\u6ce8\u518c");
																																														
																																																javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
																																																		jPanel1);
																																																jPanel1Layout.setHorizontalGroup(
																																																	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																																																		.addGroup(jPanel1Layout.createSequentialGroup()
																																																			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																																																				.addGroup(jPanel1Layout.createSequentialGroup()
																																																					.addGap(118)
																																																					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																																																						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
																																																						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE))
																																																					.addPreferredGap(ComponentPlacement.RELATED)
																																																					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																																																						.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
																																																						.addComponent(jFormattedTextField1, GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
																																																					.addGap(99))
																																																				.addGroup(jPanel1Layout.createSequentialGroup()
																																																					.addGap(124)
																																																					.addComponent(jButton2)
																																																					.addGap(18)
																																																					.addComponent(jButton3)
																																																					.addGap(18)
																																																					.addComponent(jButton4)))
																																																			.addGap(38))
																																																		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
																																																			.addGap(222)
																																																			.addComponent(jLabel2)
																																																			.addContainerGap(245, Short.MAX_VALUE))
																																																		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
																																																			.addGap(121)
																																																			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
																																																			.addContainerGap(141, Short.MAX_VALUE))
																																																);
																																																jPanel1Layout.setVerticalGroup(
																																																	jPanel1Layout.createParallelGroup(Alignment.LEADING)
																																																		.addGroup(jPanel1Layout.createSequentialGroup()
																																																			.addGap(48)
																																																			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																																																				.addGroup(jPanel1Layout.createSequentialGroup()
																																																					.addComponent(jLabel2)
																																																					.addGap(18)
																																																					.addComponent(jFormattedTextField1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
																																																				.addComponent(jLabel3))
																																																			.addGap(18)
																																																			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																																																				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
																																																				.addComponent(jLabel4))
																																																			.addGap(31)
																																																			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
																																																				.addComponent(jButton4)
																																																				.addComponent(jButton3)
																																																				.addComponent(jButton2))
																																																			.addGap(35)
																																																			.addComponent(jButton1)
																																																			.addGap(181))
																																																);
																																																jPanel1.setLayout(jPanel1Layout);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		商家注册.main(null);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		用户注册.main(null);
	}

	private void jFormattedTextField1ActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		login.setVisible(true);
	}
	private static 登陆界面 login = new 登陆界面();
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private JPanel panel;
	private JLabel lblNewLabel_1;
}