/*
 * 管理员搜索.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;

import cilent.Core;

import javax.swing.ImageIcon;
import java.awt.Rectangle;
import javax.swing.JButton;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 管理员搜索 extends javax.swing.JFrame {
	private String tmp;
	private String work1,usid,workid;
	private int page = 0;
	//private String workss [];
	/** Creates new form 管理员搜索 */
	public 管理员搜索(String tmp) {
		setIconImage(Toolkit.getDefaultToolkit().getImage(管理员搜索.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		initComponents();
		this.tmp = tmp;
		try {
			init();
		} catch (Exception e) {
			work1="找不到工作";
		}
		works.setText(work1);
	}	
	private void init() {
		String workss [] = tmp.split("下一个");
		work1 = 
				"<html>公司名称:" + workss[page].split(",")[1]
				+ "<br>工作名称:"+workss[page].split(",")[0]
				+"<br>工作岗位:"+workss[page].split(",")[2]
				+"<br>职位详细:"+workss[page].split(",")[3]
				+"<br>工作ID:"+workss[page].split(",")[4]	
				+"<br>雇主ID:"+workss[page].split(",")[5]	
				+"</html>";
		usid=workss[page].split(",")[6];
		workid=workss[page].split(",")[4];
		System.out.println(usid);
		}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setBackground(new Color(0, 204, 153));
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton1.setForeground(new Color(255, 255, 255));
		jButton1.setBackground(new Color(0, 153, 102));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (!usid.equals("0")) {
					与用户对话.main(usid);
				}else {
					JOptionPane.showMessageDialog(null, "未应聘,无法发起聊天", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}
				
			}
		});
		jButton4 = new javax.swing.JButton();
		jButton4.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton4.setBackground(new Color(0, 153, 102));
		jButton4.setForeground(new Color(255, 255, 255));
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (usid.equals("0")) {
					JOptionPane.showMessageDialog(null, "未应聘", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}else {
					JOptionPane.showMessageDialog(null, "已应聘", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});
		jButton5 = new javax.swing.JButton();
		jButton5.setBackground(new Color(0, 153, 102));
		jButton5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				page--;
				try {
					init();
					works.setText(work1);
				} catch (Exception e2) {
					JOptionPane.showMessageDialog(null, "没了", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
					page++;
				}
			}
		});
		jButton7 = new javax.swing.JButton();
		jButton7.setBackground(new Color(0, 153, 102));
		jButton7.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				page++;
				try {
					init();
					works.setText(work1);
				} catch (Exception e2) {
					JOptionPane.showMessageDialog(null, "没了", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
					page--;
				}
			}
		});

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		jPanel2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		
		works = new JLabel("New label");
		works.setFont(new Font("黑体", Font.PLAIN, 20));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addComponent(works, GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
					.addGap(20))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGap(30)
					.addComponent(works, GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		jButton1.setText("\u4e0e\u7528\u6237\u804a\u5929");

		jButton4.setText("\u67e5\u770b\u72b6\u6001");

		jButton5.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton5.setForeground(new Color(255, 255, 255));
		jButton5.setText("\u67e5\u770b\u4e0a\u4e00\u4e2a");

		jButton7.setFont(new Font("黑体", Font.PLAIN, 20));
		jButton7.setForeground(new Color(255, 255, 255));
		jButton7.setText("\u67e5\u770b\u4e0b\u4e00\u4e2a");
		
		lblNewLabel = new JLabel("\u517C\u804C\u5E73\u53F0");
		lblNewLabel.setFont(new Font("华文彩云", Font.PLAIN, 36));
		lblNewLabel.setForeground(new Color(255, 255, 255));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setForeground(new Color(255, 255, 255));
		
				jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
				jLabel1.setText("\u5df2\u5ba1\u6838\u7684\u5de5\u4f5c");
		
		lblNewLabel_1 = new JLabel("");
		lblNewLabel_1.setIcon(new ImageIcon(管理员搜索.class.getResource("/img/3.png")));
		
		JButton btnNewButton = new JButton("删除此项");
		btnNewButton.setForeground(new Color(255, 255, 255));
		btnNewButton.setBackground(new Color(0, 153, 102));
		btnNewButton.setFont(new Font("黑体", Font.PLAIN, 20));
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				Core.delworkInfo(workid);
				JOptionPane.showMessageDialog(null, "已执行", "MESSAGE", JOptionPane.INFORMATION_MESSAGE);
				try {
					init();
				} catch (Exception e2) {
					// TODO: handle exception
				}
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(33)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
									.addGap(18)
									.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel1)
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(lblNewLabel))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(87)
							.addComponent(lblNewLabel_1)))
					.addContainerGap(94, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(lblNewLabel)
					.addGap(34)
					.addComponent(jLabel1)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton7, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
					.addGap(5)
					.addComponent(lblNewLabel_1)
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
					.addGap(1))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 749, Short.MAX_VALUE)
					.addGap(1))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 管理员搜索(args).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private JLabel works;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
}