/*
 * 管理员注册.java
 *
 * Created on __DATE__, __TIME__
 */

package cilent.gui;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import cilent.Core;
import cilent.infor.regAdmin;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  __USER__
 */
public class 管理员注册 extends javax.swing.JFrame {

	/** Creates new form 管理员注册 */
	public 管理员注册() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(管理员注册.class.getResource("/img/\u5FAE\u4FE1\u56FE\u7247tb.jpg")));
		setBounds(new Rectangle(560, 110, 0, 0));
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		JPanel panel = new JPanel();
		panel.setBackground(new Color(0, 204, 153));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 753, Short.MAX_VALUE)
					.addGap(1))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(panel, GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
					.addGap(1))
		);
				
						jPanel1 = new javax.swing.JPanel();
						panel.add(jPanel1);
						jLabel1 = new javax.swing.JLabel();
						jLabel1.setForeground(new Color(0, 204, 153));
						jLabel2 = new javax.swing.JLabel();
						jLabel2.setBackground(new Color(0, 204, 153));
						jLabel3 = new javax.swing.JLabel();
						jLabel4 = new javax.swing.JLabel();
						jLabel5 = new javax.swing.JLabel();
						jFormattedTextField1 = new javax.swing.JFormattedTextField();
						jFormattedTextField2 = new javax.swing.JFormattedTextField();
						jPasswordField1 = new javax.swing.JPasswordField();
						jPasswordField2 = new javax.swing.JPasswordField();
						jButton1 = new javax.swing.JButton();
						
								jPanel1.setBackground(new Color(255, 255, 255));
								
										jLabel1.setFont(new java.awt.Font("黑体", 0, 36));
										jLabel1.setText("\u7ba1\u7406\u5458\u6ce8\u518c");
										
												jLabel2.setFont(new java.awt.Font("黑体", 0, 24));
												jLabel2.setForeground(new Color(0, 204, 153));
												jLabel2.setText("\u5e10\u53f7");
												
														jLabel3.setFont(new java.awt.Font("黑体", 0, 24));
														jLabel3.setForeground(new Color(0, 204, 153));
														jLabel3.setText("\u5bc6\u7801");
														
																jLabel4.setFont(new java.awt.Font("黑体", 0, 24));
																jLabel4.setForeground(new Color(0, 204, 153));
																jLabel4.setText("\u786e\u8ba4\u5bc6\u7801");
																
																		jLabel5.setFont(new java.awt.Font("黑体", 0, 24));
																		jLabel5.setForeground(new Color(0, 204, 153));
																		jLabel5.setText("\u5de5\u4f5c\u5c97\u4f4d");
																		
																				jFormattedTextField2
																						.addActionListener(new java.awt.event.ActionListener() {
																							public void actionPerformed(java.awt.event.ActionEvent evt) {
																								jFormattedTextField2ActionPerformed(evt);
																							}
																						});
																				
																						jButton1.setBackground(new Color(0, 204, 153));
																						jButton1.setFont(new java.awt.Font("黑体", 0, 24));
																						jButton1.setForeground(new Color(255, 255, 255));
																						jButton1.setText("\u6ce8\u518c");
																						jButton1.addActionListener(new java.awt.event.ActionListener() {
																							public void actionPerformed(java.awt.event.ActionEvent evt) {
																								jButton1ActionPerformed(evt);
																							}
																						});
																						
																								javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
																										jPanel1);
																								jPanel1Layout.setHorizontalGroup(
																									jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																										.addGroup(jPanel1Layout.createSequentialGroup()
																											.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																												.addGroup(jPanel1Layout.createSequentialGroup()
																													.addGap(56)
																													.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																														.addGroup(jPanel1Layout.createSequentialGroup()
																															.addComponent(jLabel3)
																															.addGap(18)
																															.addComponent(jPasswordField1, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
																														.addGroup(jPanel1Layout.createSequentialGroup()
																															.addComponent(jLabel2)
																															.addGap(18)
																															.addComponent(jFormattedTextField1, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))))
																												.addGroup(jPanel1Layout.createSequentialGroup()
																													.addContainerGap()
																													.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																														.addComponent(jLabel4)
																														.addComponent(jLabel5))
																													.addGap(12)
																													.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																														.addComponent(jFormattedTextField2, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
																														.addComponent(jPasswordField2, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))))
																											.addGap(44))
																										.addGroup(jPanel1Layout.createSequentialGroup()
																											.addGap(172)
																											.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
																											.addContainerGap(186, Short.MAX_VALUE))
																										.addGroup(jPanel1Layout.createSequentialGroup()
																											.addGap(170)
																											.addComponent(jLabel1)
																											.addContainerGap(212, Short.MAX_VALUE))
																								);
																								jPanel1Layout.setVerticalGroup(
																									jPanel1Layout.createParallelGroup(Alignment.LEADING)
																										.addGroup(jPanel1Layout.createSequentialGroup()
																											.addGap(11)
																											.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
																											.addGap(18)
																											.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
																												.addComponent(jLabel2)
																												.addComponent(jFormattedTextField1, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
																											.addPreferredGap(ComponentPlacement.RELATED)
																											.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
																												.addComponent(jLabel3)
																												.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
																											.addGap(10)
																											.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
																												.addComponent(jLabel4)
																												.addComponent(jPasswordField2, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
																											.addPreferredGap(ComponentPlacement.RELATED)
																											.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
																												.addComponent(jLabel5)
																												.addComponent(jFormattedTextField2, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
																											.addGap(27)
																											.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
																											.addGap(53))
																								);
																								jPanel1.setLayout(jPanel1Layout);
				
				lblNewLabel_1 = new JLabel("");
				lblNewLabel_1.setIcon(new ImageIcon(管理员注册.class.getResource("/img/3.png")));
				panel.add(lblNewLabel_1);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		regAdmin rA = new regAdmin();
		rA.setName(jFormattedTextField1.getText());
		rA.setPw(String.copyValueOf(jPasswordField1.getPassword()));
		rA.setJob(jFormattedTextField2.getText());
		String rString=Core.regA(rA.toString());
		System.out.println(rString);
		if (rString.equals("true")) {
			JOptionPane.showMessageDialog(null,"注册成功", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
			dispose();
		}else {
			JOptionPane.showMessageDialog(null,"注册失败", "MESSAGE",JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 管理员注册().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JFormattedTextField jFormattedTextField1;
	private javax.swing.JFormattedTextField jFormattedTextField2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private JLabel lblNewLabel_1;
}